# HTTP
quarkus.http.port=8080

# Datasource (produção via variáveis de ambiente; dev/test usam Dev Services)
quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${DB_USER}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${DB_URL}

# Hibernate / ORM
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true

# JWT
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://seavault.irontech.dev.br
smallrye.jwt.sign.key.location=${JWT_PRIVATE_KEY_LOCATION:privateKey.pem}
seavault.jwt.access-ttl-seconds=900
seavault.jwt.refresh-ttl-days=30
seavault.auth.confirm-token-ttl-hours=48
seavault.auth.reset-token-ttl-hours=2
seavault.app.base-url=http://localhost:8080

# Mailer (mock em dev/test; real em prod via env)
quarkus.mailer.from=no-reply@seavault.irontech.dev.br
%dev.quarkus.mailer.mock=true
%test.quarkus.mailer.mock=true

# OpenAPI
quarkus.smallrye-openapi.info-title=SeaVault API
quarkus.smallrye-openapi.info-version=1.0.0
